name: Stock Scanner Automation

on:
  schedule:
    - cron: '0 11 * * 1-5' # 평일 밤 8시
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v3에서 v4로 업데이트

      - name: Set up Python
        uses: actions/setup-python@v5 # v4에서 v5로 업데이트
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python my_scanner.py
